In [14]:
import numpy as np

In [15]:
minha_lista = [1, 2, 3]

In [16]:
minha_lista

[1, 2, 3]

In [17]:
np.array(minha_lista)

array([1, 2, 3])

In [18]:
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(5, 8)

array([5, 6, 7])

In [24]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [25]:
np.zeros([5, 5])

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [26]:
np.ones([3,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [27]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [28]:
np.linspace(0, 10, 2)

array([  0.,  10.])

In [29]:
np.linspace(0, 10, 4)

array([  0.        ,   3.33333333,   6.66666667,  10.        ])

In [30]:
np.linspace(0, 10, 5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [31]:
np.random.rand(5)

array([ 0.95274676,  0.02384772,  0.6824097 ,  0.53435646,  0.99475358])

In [32]:
np.random.rand(5) * 100

array([  6.24016141,  89.62846538,  88.40546827,  84.87749933,  58.63574332])

In [33]:
np.random.rand(5, 4)

array([[ 0.63953713,  0.92178855,  0.12997533,  0.40802236],
       [ 0.95875801,  0.71991228,  0.64757635,  0.01838527],
       [ 0.43024232,  0.51455366,  0.73126188,  0.92740105],
       [ 0.6465506 ,  0.90924336,  0.18559123,  0.35239934],
       [ 0.08993377,  0.49986518,  0.74504563,  0.41985848]])

In [34]:
np.random.randn(4)

array([ 0.86176481,  1.50087543,  0.2551327 , -0.08316129])

In [35]:
np.random.randint(0, 100, 10)

array([31,  3, 67, 73, 60, 11, 84, 40, 71, 80])

In [36]:
arr = np.random.rand(25)

In [37]:
arr

array([ 0.52071438,  0.58950648,  0.8775357 ,  0.89830368,  0.76582927,
        0.02604283,  0.99351436,  0.73132818,  0.41213405,  0.01864957,
        0.4404562 ,  0.50978686,  0.0527181 ,  0.59213104,  0.98495826,
        0.05182899,  0.56726121,  0.77940483,  0.83740036,  0.46424122,
        0.75690241,  0.84433807,  0.87015452,  0.56834846,  0.63425371])

In [40]:
arr.reshape([5,5])

array([[ 0.52071438,  0.58950648,  0.8775357 ,  0.89830368,  0.76582927],
       [ 0.02604283,  0.99351436,  0.73132818,  0.41213405,  0.01864957],
       [ 0.4404562 ,  0.50978686,  0.0527181 ,  0.59213104,  0.98495826],
       [ 0.05182899,  0.56726121,  0.77940483,  0.83740036,  0.46424122],
       [ 0.75690241,  0.84433807,  0.87015452,  0.56834846,  0.63425371]])

In [41]:
arr = arr.reshape([5,5])

In [42]:
arr

array([[ 0.52071438,  0.58950648,  0.8775357 ,  0.89830368,  0.76582927],
       [ 0.02604283,  0.99351436,  0.73132818,  0.41213405,  0.01864957],
       [ 0.4404562 ,  0.50978686,  0.0527181 ,  0.59213104,  0.98495826],
       [ 0.05182899,  0.56726121,  0.77940483,  0.83740036,  0.46424122],
       [ 0.75690241,  0.84433807,  0.87015452,  0.56834846,  0.63425371]])

In [43]:
arr.shape

(5, 5)

In [44]:
arr.max()

0.99351436083985534

In [45]:
arr.min()

0.018649571851591662

In [46]:
arr.argmax()

6